### ISSUE TITLE
希望支持动态日期范围限制

### ISSUE THREAD

**Issue by yiqing** [sentsin/laydate#11]
仅仅是期望 feature 
在选择日期区间功能上  经常出现 第二个日期控件的min 最小时间是 第一个控件选择后的时间

期望使用方式： min : function(){   // return 第一个时间控件的当前时间      }   或者 minRel = '#selector1'

这样后一个控件可能要监听第一个控件的“变化” 事件  每当第一个控件选择了新值后 第二个控件需要判断自己的时间 是否 >= 大于等于 前一个时间控件的值
如果比第一个时间小 那么需要调整自己的可用日期范围 ....

**Comment by yiqing** [comment]
对不起 没仔细看文档 好像已经有这种功能了
请关闭该issure

**Comment by sentsin** [comment]
还有什么问题欢迎再提，本周layDate会发布1.2
