### ISSUE TITLE
时间具体到“秒”，现在是点击完“日”，弹窗就关闭了，可否控制到点击“秒”才关闭？

### ISSUE THREAD

**Issue by pigerla** [sentsin/laydate#19]
时间具体到“秒”，现在是点击完“日”，弹窗就关闭了，可否控制到点击“秒”才关闭？

**Comment by sentsin** [comment]
额，1.1没有做这方面的处理，不过你暂时可以修改源码

**Comment by pigerla** [comment]
尝试修改源码，发现选定“秒”没有对应处理？！

**Comment by FlyCloud1006** [comment]
重写对#laydate_table td的绑定，就可以点击日时，不会关闭弹窗，但是时间要，点击确定

Dates.each(S("#laydate_table td"),
        function(i, elem) {
            Dates.on(elem, "click",
            function(ev) {
                if (!Dates.hasClass(this, as[1])) {

                    if( Dates.options.format =="YYYY-MM-DD"){
                        Dates.stopmp(ev);
                        Dates.creation([this.getAttribute("y") | 0, this.getAttribute("m") | 0, this.getAttribute("d") | 0])
                    }else{ //该处解决在选择日期，时间时。点击日，时间控件就会关闭
                        Dates.stopmp(ev);
                        //Dates.creation()方法，会关闭弹出选择时间控件
                        Dates.viewDate(this.getAttribute("y") | 0, (this.getAttribute("m") | 0) - 1, this.getAttribute("d") | 0);
                    }
                }
            })
        });
